global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'postgres'
    static_configs:
      - targets: ['172.16.14.53:9187']
    params:
      user: ['postgres']
      password: ['postgrespassword']
      dbname: ['shop']
