global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['172.16.14.53:9100']

  - job_name: 'postgres-exporter'
    static_configs:
      - targets: ["172.16.14.53:9187"]

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["172.16.14.53:9093"]
